export const MyAction = {
  DARK: "DARK",
  LIGHT: "LIGHT",
  FETCH: "FETCHING",
  RECEIVE: "RECEIVED",
  ADDTOMYLIST: "SETMYLIST",
  GETALLLIST: "GETALLLIST",
  ADDTOWATCHLIST : "SETMYWATCHLIST",
  GETALLWATCHLIST : "GETALLWATCHLIST",
  CLEARWATCHLIST : "CLEARWATCHLIST",
  REMOVEFROMLIST: "REMOVEFROMLIST",
  FALSELOADING: "FALSELOADING",
  RESUMEID: "RESUMEID",
};
